import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  Aldrich,
  Dosis,
  Electrolize,
  Lato,
  Open_Sans,
  Roboto,
  Ubuntu,
} from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const openSans = Open_Sans({
  weight: ["400", "300", "500"],
  style: ["normal"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className}  antialiased`}>{children}</body>
    </html>
  );
}
